[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["find .next/cache -mindepth 1 -delete 2>/dev/null; npm run build"]

[start]
cmd = "node server.js"
